// ** React Imports

// ** MUI Imports

// ** Custom Component Import

// ** Third Party Imports

// ** Icon Imports
import Icon from 'src/@core/components/icon'
import SelectBox from './ui/SelectBox'
import { Button, Grid } from '@mui/material'
import { useState } from 'react'
import { useRouter } from 'next/router'
import api from 'src/lib/api'
import Error500 from 'src/pages/500'
import Loading from './Loading'
import UseQueryHooks from 'src/lib/react-query'

// ** Store Imports

// ** Actions Imports

// interface NicheResponse {
//   label: string
//   value: string
// }
const FiltersInfluenceurs = () => {
  // ** Props

  const router = useRouter()

  // /creators/search?networks=ig,tk&categories=id1,id2,id3&country=504(id du pays, tu le recois via /countries et c l'iso36jsaispluscombien par un id autogenerated)&gender=F&range=30,300

  // const scoreList = [
  //   { label: 'Audience Growth', value: 'audienceGrowth' },
  //   { label: 'Instagram Score', value: 'instagramScore' },
  //   { label: 'Tiktok Score', value: 'tiktokScore' },
  //   { label: 'Youtube Score', value: 'youtubeScore' },
  //   { label: 'Twitter Score', value: 'twitterScore' },
  //   { label: 'Linkedin Score', value: 'linkedinScore' },
  //   { label: 'Instagram Followers', value: 'instagramFollowers' },
  //   { label: 'Tiktok Followers', value: 'tiktokFollowers' }
  // ]

  const socialMediaList = [
    {
      label: 'Twitter',
      value: 'TT',
      image: '/images/social-media/twitter.png'
    },
    {
      label: 'Instagram',
      value: 'IG',
      image: '/images/social-media/instagram.png'
    },
    {
      label: 'LinkedIn',
      value: 'LD',
      image: '/images/social-media/linkedin.png'
    },
    {
      label: 'YouTube',
      value: 'YT',
      image: '/images/social-media/youtube.png'
    },
    {
      label: 'TikTok',
      value: 'TK',
      image: '/images/social-media/tiktok.png'
    },
    {
      label: 'Snapchat',
      value: 'SC',
      image: '/images/social-media/snapchat.png'
    }
  ]

  // const influencerCategories = ['nano', 'micro', 'micro', 'celebrities']
  const influencerCategories = [
    {
      label: 'Nano (1k - 30k)',
      value: 'nano'
    },
    {
      label: 'Micro (31k - 300k)',
      value: 'micro'
    },
    {
      label: 'Macro (300k - 2M)',
      value: 'macro'
    },
    {
      label: 'Celebrities ( +2M)',
      value: 'celebrities'
    }
  ]

  const genders = [
    {
      label: 'Male',
      value: 'M',
      image: '/images/icons/male.png'
    },
    {
      label: 'Female',
      value: 'F',
      image: '/images/icons/female.png'
    }
  ]

  // const { influencerCategory, category, networks, gender }
  const { influencerCategory, networks, gender } = router.query as {
    influencerCategory?: string
    category?: string
    networks?: string
    gender?: string
  }

  const [filters, setFilters] = useState({
    influencerCategory: '0',
    orderBy: '0',
    category: '0',
    networks: '0',
    gender: '0',
    country: ''
  })

  const setTheFilters = () => {
    router.push({
      query: { ...router.query, ...filters }
    })
  }

  // const { error, isLoading, data } = UseQueryHooks<NicheResponse[]>(['categories'], async () => {
  //   const response = await api.get<any>('/categories')

  //   return response.data
  // })

  // if (isLoading) return <Loading />
  // if (error) return <Error500 />

  const {
    error: errorCountries,
    isLoading: countriesLoading,
    data: countries
  } = UseQueryHooks<any>(['countries'], async () => {
    const response = await api.get<any>('/countries')

    return response.data
  })

  if (errorCountries) return <Loading />
  if (countriesLoading) return <Error500 />

  return (
    <form action='' method='get' style={{ width: '100%' }}>
      <Grid container mt={2} spacing={6} sx={{ alignItems: 'end' }}>
        <Grid item xs={2}>
          <SelectBox
            handleChange={e => {
              setFilters({ ...filters, networks: e })
            }}
            items={socialMediaList}
            defaultValue={networks}
            value={filters.networks}
            label='Social Media'
            id='social-media'
          />
        </Grid>
        <Grid item xs={2}>
          {/* {JSON.stringify(data)} */}
          {/* {data && data.length > 0 && (
            <>
              <SelectBox
                handleChange={e => {
                  setFilters({ ...filters, category: e })
                }}
                items={data}
                label='Niche'
                value={filters.category}
                defaultValue={category}
                id='category'
              />
            </>
          )} */}
        </Grid>

        <Grid item xs={2}>
          <SelectBox
            handleChange={e => {
              setFilters({ ...filters, influencerCategory: e })
            }}
            items={influencerCategories}
            label='Influencer category'
            value={filters.influencerCategory}
            defaultValue={influencerCategory}
            id='influencerCategory'
          />
        </Grid>

        <Grid item xs={2}>
          <SelectBox
            handleChange={e => {
              setFilters({ ...filters, gender: e })
            }}
            items={genders}
            defaultValue={gender}
            value={filters.gender}
            label='All Genders'
            id='gender'
          />
        </Grid>
        <Grid item xs={2}>
          <SelectBox
            handleChange={e => {
              setFilters({ ...filters, country: e })
            }}
            items={countries}
            defaultValue='0'
            label='Country'
            id='country'
          />
        </Grid>
        <Grid item xs={2}>
          <div
            style={{
              display: 'flex',
              gap: '10px'
            }}
          >
            <Button color='primary' onClick={() => setTheFilters()} variant='contained' sx={{ '& svg': { mr: 1 } }}>
              <Icon fontSize='1.125rem' icon='tabler:search' />
              Search
            </Button>
            <Button
              type='button'
              onClick={() => {
                router.push(router.pathname)
                setFilters({
                  orderBy: '0',
                  influencerCategory: '0',
                  category: '0',
                  networks: '0',
                  gender: '0',
                  country: ''
                })
              }}
              variant='outlined'
              sx={{ '& svg': { mr: 1 } }}
            >
              <Icon fontSize='1.125rem' icon='tabler:refresh' />
            </Button>
          </div>
        </Grid>
      </Grid>
    </form>
  )
}

export default FiltersInfluenceurs
